[General]
key_pmi=5740205656
key_pmi_invite_msg="Ramirez Dominguez Aldo Eduardo is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Sala de reuniones personales de Ramirez Dominguez Aldo Eduardo\r\n\r\nJoin Zoom Meeting\r\nhttps://us04web.zoom.us/j/5740205656?pwd=ZFkvRUxLd0FGN2p1TWZXNVRCWXNnQT09\r\n\r\nMeeting ID: 574 020 5656\r\nPasscode: P499gF\r\n\r\n"
