#Themes
#include themes/dracula.conf
#include themes/gruvbox-dark.conf
#include themes/gruvbox-material-dark-hard.conf
include themes/gruvbox-material-dark-medium.conf

#Fonts
font_family      JetBrains Mono Nerd Font 
bold_font        JetBrains Mono Nerd Font Bold
italic_font      JetBrains Mono Nerd Font Italic 
bold_italic_font JetBrains Mono Nerd Font Bold Italic

font_size 14.0

#General Settings
window_padding_width 30

background_opacity 1

enable_audio_bell no

window_border_width 0.5pt

#Tabs
tab_bar_style fade

#Layouts
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map F4 launch --location=hsplit
map F5 launch --location=vsplit
map F7 layout_action rotate

map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter 3

enabled_layouts splits:split_axis=horizontal

┌──────────────┬───────────────┐
│              │               │
│              │               │
│              │               │
│              ├───────┬───────┤
│              │       │       │
│              │       │       │
│              │       │       │
│              ├───────┴───────┤
│              │               │
│              │               │
│              │               │
└──────────────┴───────────────┘
