# cbatticon
# Autogenerated from man page /usr/share/man/man1/cbatticon.1.gz
complete -c cbatticon -s c -l command-critical-level -d 'Specify the command to execute when the critical battery level is reached'
complete -c cbatticon -s d -l debug -d 'Display debug information'
complete -c cbatticon -s h -l help -d 'Show help information and exit'
complete -c cbatticon -s i -l icon-type -d 'Specify the icon type to display in the system tray'
complete -c cbatticon -s l -l low-level -d 'Specify the low level percentage of the battery. br The default is set to 20%'
complete -c cbatticon -s n -l hide-notification -d 'Hide the notification popups'
complete -c cbatticon -s p -l list-power-supplies -d 'List the available power supplies on your system'
complete -c cbatticon -s r -l critical-level -d 'Specify the critical level percentage of the battery'
complete -c cbatticon -s t -l list-icon-types -d 'List the available icon types (standard, notification, symbolic)'
complete -c cbatticon -s u -l update-interval -d 'Specify the number of seconds between updates of the battery information'
complete -c cbatticon -s v -l version -d 'Display the version information and exit'

