[module/brightness]
type = internal/backlight
enable-scroll = true
card = amdgpu_bl0

format = <ramp>
format-background = ${colors.background}
format-foreground = ${colors.light}
format-padding = 0

ramp-0 = " "
ramp-1 = " "
ramp-2 = " "
ramp-3 = " "
ramp-4 = " "
ramp-5 = " "
ramp-6 = " "
ramp-7 = " "
ramp-8 = " "
ramp-9 = " "


[module/brightnessSlider]
type = internal/backlight
enable-scroll = true
use-actual-brightness = true

card = amdgpu_bl0

format = <bar>
format-padding = 1
format-background = ${colors.background}

bar-width = 10
bar-gradient = false
bar-indicator = 雷
bar-indicator-foreground = ${colors.light}
bar-fill = 絛
bar-foreground-0 = ${colors.light}
bar-foreground-1 = ${colors.light}
bar-foreground-2 = ${colors.light}
bar-empty = 絛
bar-empty-foreground = ${colors.inactive}

; vim:ft=dosini
