[module/LA]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.transparent}
content-foreground = ${colors.background}

[module/LB]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.transparent}
content-foreground = ${colors.light}

[module/LC]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.light}

; vim:ft=dosini
