[module/network]
type = internal/network
interface = wlp2s0

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-foreground = ${colors.light}
# format-connected-prefix = " "
format-connected-prefix-background = ${colors.background}
format-connected-prefix-foreground = ${colors.light}

format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.light}
# format-disconnected-prefix = "睊 "
format-disconnected-prefix-background = ${colors.background}
format-disconnected-prefix-foreground = ${colors.light}

label-connected = " "
label-disconnected = "睊 "

label-connected-background = ${colors.background} 
label-disconnected-background = ${colors.background}

; vim:ft=dosini
