[module/RA]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.transparent}
content-foreground = ${colors.background}

[module/RB]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.transparent}
content-foreground = ${colors.light}

[module/RC]
type = custom/text
content = %{T2}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.light}
; vim:ft=dosini



