[module/spcFB]
type = custom/text
content = " "
content-background = ${colors.background}
content-foreground = ${colors.background}

[module/spcFL]
type = custom/text
content = " "
content-background = ${colors.light}
content-foreground = ${colors.light}

[module/spcT]
type = custom/text
content = " "
content-background = ${colors.transparent}
content-foreground = ${colors.transparent}



; vim:ft=dosini

