[module/volume]
type = internal/pulseaudio
click-right = pavucontrol

format-volume = <ramp-volume>
format-volume-background = ${colors.background}
format-volume-foreground = ${colors.light}
format-volume-padding = 0

format-muted-background = ${colors.background}
format-muted-foreground = ${colors.light}
format-muted-padding = 0

label-muted = "婢 "
label-muted-font = 1
label-muted-foreground = ${colors.light}

ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = " "
ramp-volume-font = 1

[module/volumeSlider]
type = internal/pulseaudio
click-right = pavucontrol

format-volume = <bar-volume>
format-volume-padding = 1
format-volume-font = 1
format-volume-background = ${colors.background}

format-muted-background = ${colors.background}
format-muted-foreground = ${colors.light}
format-muted-padding = 1

label-muted = Muted
label-muted-foreground = ${colors.light}

bar-volume-width = 10
bar-volume-gradient = false
bar-volume-indicator = 雷
bar-volume-indicator-foreground = ${colors.light}
bar-volume-fill = 絛
bar-volume-foreground-0 = ${colors.light}
bar-volume-foreground-1 = ${colors.light}
bar-volume-foreground-2 = ${colors.light}
bar-volume-empty = 絛
bar-volume-empty-foreground = ${colors.inactive}

; vim:ft=dosini
