#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Screens
hdmi=`xrandr | grep ' connected' | grep 'HDMI-A-0' | awk '{print $1}'`

if [ "$hdmi" = "HDMI-A-0" ]; then
  sh /home/aldo/.screenlayout/resolution.sh &
  bspc monitor HDMI-A-0 -d I II III IV V 
  bspc monitor eDP -d VI VII VIII IX X
else
  xrandr --output eDP --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-0 --off &
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Polybar
$HOME/.config/polybar/launch.sh

# BSPWM CONFIG
bspc config border_width            3
bspc config window_gap              12
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true

bspc config top_padding          0  
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  true

bspc config focused_border_color '#ffffff'
bspc config normal_border_color '#1d2021'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Composer
picom &

# Notifiaction
dunst &

# Wallpaper
source ~/.fehbg

# Keyboard
setxkbmap latam

# Network
killall -q nm-applet
nm-applet &

# Automount Devices
killall -q udiskie
udiskie -a -t &

# Mouse Settings
xinput set-prop "SYN3000:00 06CB:7F28 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYN3000:00 06CB:7F28 Touchpad" "libinput Natural Scrolling Enabled" 1
